-- PolPro üretim veritabanı şeması
-- Supabase Dashboard > SQL Editor üzerinden bir kez çalıştırın.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'Görüntüleyici'
    check (role in ('Yönetici', 'Kullanıcı', 'Görüntüleyici')),
  category text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.current_app_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() and active = true $$;

create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), 'Görüntüleyici')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.create_profile_for_new_user();

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  client text,
  manager text,
  team jsonb not null default '[]'::jsonb,
  scope text,
  objective text,
  priority text not null default 'Orta',
  project_status text not null default 'Planlama',
  completion numeric(5,2),
  folder_url text,
  technical_url text,
  start_date date not null,
  end_date date not null,
  budget numeric(14,2) not null default 0 check (budget >= 0),
  color text not null default '#5b5bd6',
  cover_image_path text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

alter table public.projects add column if not exists code text;
alter table public.projects add column if not exists team jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists scope text;
alter table public.projects add column if not exists objective text;
alter table public.projects add column if not exists priority text not null default 'Orta';
alter table public.projects add column if not exists project_status text not null default 'Planlama';
alter table public.projects add column if not exists completion numeric(5,2);
alter table public.projects add column if not exists folder_url text;
alter table public.projects add column if not exists technical_url text;
create unique index if not exists projects_code_unique_idx on public.projects(code) where code is not null;

create table if not exists public.project_managers (
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  primary key (project_id, user_id)
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  assignee text not null,
  assignee_id uuid references public.profiles(id),
  status text not null default 'todo' check (status in ('todo','doing','done')),
  priority text not null default 'Orta' check (priority in ('Yüksek','Orta','Düşük')),
  start_date date not null,
  end_date date not null,
  work_package text,
  accountable text,
  consulted jsonb not null default '[]'::jsonb,
  informed jsonb not null default '[]'::jsonb,
  actual_start_date date,
  actual_end_date date,
  predecessor_id bigint references public.tasks(id) on delete set null,
  completion numeric(5,2) not null default 0,
  description text,
  delay_reason text,
  milestone boolean not null default false,
  milestone_name text,
  resource_group text,
  effort_hours numeric(10,2) not null default 0,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

alter table public.tasks add column if not exists work_package text;
alter table public.tasks add column if not exists accountable text;
alter table public.tasks add column if not exists consulted jsonb not null default '[]'::jsonb;
alter table public.tasks add column if not exists informed jsonb not null default '[]'::jsonb;
alter table public.tasks add column if not exists actual_start_date date;
alter table public.tasks add column if not exists actual_end_date date;
alter table public.tasks add column if not exists predecessor_id bigint references public.tasks(id) on delete set null;
alter table public.tasks add column if not exists completion numeric(5,2) not null default 0;
alter table public.tasks add column if not exists description text;
alter table public.tasks add column if not exists delay_reason text;
alter table public.tasks add column if not exists milestone boolean not null default false;
alter table public.tasks add column if not exists milestone_name text;
alter table public.tasks add column if not exists resource_group text;
alter table public.tasks add column if not exists effort_hours numeric(10,2) not null default 0;

create table if not exists public.costs (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  expense_date date not null,
  description text not null,
  category text not null,
  vendor text,
  amount numeric(14,2) not null check (amount >= 0),
  budget_amount numeric(14,2) not null default 0 check (budget_amount >= 0),
  ordered_amount numeric(14,2) not null default 0 check (ordered_amount >= 0),
  remaining_estimate numeric(14,2) not null default 0 check (remaining_estimate >= 0),
  currency char(3) not null default 'TRY' check (currency in ('TRY','EUR','USD')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.costs
  alter column project_id drop not null;
alter table public.costs add column if not exists budget_amount numeric(14,2) not null default 0;
alter table public.costs add column if not exists ordered_amount numeric(14,2) not null default 0;
alter table public.costs add column if not exists remaining_estimate numeric(14,2) not null default 0;

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  contact text,
  phone text,
  email text,
  category text,
  status text not null default 'Aktif',
  created_at timestamptz not null default now()
);

create table if not exists public.project_files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  mime_type text,
  size_bytes bigint not null check (size_bytes between 0 and 15728640),
  uploaded_by uuid references public.profiles(id),
  uploaded_at timestamptz not null default now()
);

alter table public.project_files
  add column if not exists task_id bigint references public.tasks(id) on delete cascade;

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  actor_name text not null,
  action text not null,
  detail text,
  kind text not null default 'update',
  created_at timestamptz not null default now()
);

create table if not exists public.procurements (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  material_code text not null,
  material_description text not null,
  technical_spec text,
  quantity numeric(14,3) not null default 0,
  request_date date not null,
  quote_status text not null default 'Talep Açıldı',
  vendor text,
  order_date date,
  due_date date not null,
  actual_delivery_date date,
  received_quantity numeric(14,3) not null default 0,
  quality_result text not null default 'Bekliyor',
  owner text,
  long_lead boolean not null default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.manufacturings (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  operation text not null,
  description text not null,
  resource_group text,
  responsible text,
  planned_start date not null,
  planned_end date not null,
  actual_start date,
  actual_end date,
  planned_quantity numeric(14,3) not null default 0,
  produced_quantity numeric(14,3) not null default 0,
  completion numeric(5,2) not null default 0,
  status text not null default 'Planlandı',
  created_at timestamptz not null default now(),
  check (planned_end >= planned_start)
);

create table if not exists public.risks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  description text not null,
  probability text not null,
  impact text not null,
  owner text,
  preventive_action text,
  contingency_plan text,
  target_date date not null,
  status text not null default 'Açık',
  created_at timestamptz not null default now()
);

create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  description text not null,
  owner text,
  corrective_action text,
  target_date date not null,
  status text not null default 'Açık',
  created_at timestamptz not null default now()
);

create table if not exists public.changes (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  request text not null,
  requested_by text,
  reason text,
  technical_impact text,
  schedule_impact_days integer not null default 0,
  cost_impact numeric(14,2) not null default 0,
  approval_status text not null default 'Taslak',
  responsible text,
  revision text,
  created_at timestamptz not null default now()
);

create table if not exists public.actions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  meeting_date date not null,
  meeting_title text not null,
  decision text not null,
  action text not null,
  owner text,
  target_date date not null,
  status text not null default 'Açık',
  related_task_id bigint references public.tasks(id) on delete set null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.document_revisions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  file_id bigint references public.project_files(id) on delete set null,
  document_type text not null,
  document_no text not null,
  revision text not null,
  revision_date date not null,
  prepared_by text,
  checked_by text,
  approved_by text,
  approval_status text not null default 'Taslak',
  revision_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.quality_records (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  control_type text not null,
  status text not null default 'Planlandı',
  nonconformity text,
  photo_url text,
  department text,
  corrective_action text,
  closure_date date,
  approved_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.project_closures (
  id bigint generated by default as identity primary key,
  project_id bigint not null unique references public.projects(id) on delete cascade,
  actual_end date not null,
  total_cost numeric(14,2) not null default 0,
  open_items text,
  warranty_start date,
  warranty_end date,
  spare_parts text,
  maintenance_plan text,
  manual_url text,
  lessons_learned text,
  customer_satisfaction smallint check (customer_satisfaction between 1 and 5),
  approved_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.capacity_records (
  id bigint generated by default as identity primary key,
  name text not null unique,
  monthly_capacity numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists tasks_project_id_idx on public.tasks(project_id);
create index if not exists tasks_dates_idx on public.tasks(start_date, end_date);
create index if not exists costs_project_id_idx on public.costs(project_id);
create index if not exists activities_project_time_idx on public.activities(project_id, created_at desc);
create index if not exists project_files_project_id_idx on public.project_files(project_id);
create index if not exists project_files_task_id_idx on public.project_files(task_id);
create index if not exists procurements_project_due_idx on public.procurements(project_id, due_date);
create index if not exists manufacturings_project_dates_idx on public.manufacturings(project_id, planned_start, planned_end);
create index if not exists risks_project_status_idx on public.risks(project_id, status);
create index if not exists issues_project_status_idx on public.issues(project_id, status);
create index if not exists actions_project_target_idx on public.actions(project_id, target_date);
create index if not exists document_revisions_project_no_idx on public.document_revisions(project_id, document_no, revision_date desc);
create index if not exists quality_records_project_idx on public.quality_records(project_id);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_managers enable row level security;
alter table public.tasks enable row level security;
alter table public.costs enable row level security;
alter table public.suppliers enable row level security;
alter table public.project_files enable row level security;
alter table public.activities enable row level security;
alter table public.procurements enable row level security;
alter table public.manufacturings enable row level security;
alter table public.risks enable row level security;
alter table public.issues enable row level security;
alter table public.changes enable row level security;
alter table public.actions enable row level security;
alter table public.document_revisions enable row level security;
alter table public.quality_records enable row level security;
alter table public.project_closures enable row level security;
alter table public.capacity_records enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (true);
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated
using (public.current_app_role() = 'Yönetici')
with check (public.current_app_role() = 'Yönetici');

do $$
declare table_name text;
begin
  foreach table_name in array array['projects','project_managers','tasks','costs','suppliers','project_files','activities','procurements','manufacturings','risks','issues','changes','actions','document_revisions','quality_records','project_closures','capacity_records']
  loop
    execute format('drop policy if exists %I_read on public.%I', table_name, table_name);
    execute format('create policy %I_read on public.%I for select to authenticated using (true)', table_name, table_name);
    execute format('drop policy if exists %I_insert on public.%I', table_name, table_name);
    execute format('create policy %I_insert on public.%I for insert to authenticated with check (public.current_app_role() in (''Yönetici'',''Kullanıcı''))', table_name, table_name);
    execute format('drop policy if exists %I_update on public.%I', table_name, table_name);
    execute format('create policy %I_update on public.%I for update to authenticated using (public.current_app_role() in (''Yönetici'',''Kullanıcı'')) with check (public.current_app_role() in (''Yönetici'',''Kullanıcı''))', table_name, table_name);
    execute format('drop policy if exists %I_delete on public.%I', table_name, table_name);
    execute format('create policy %I_delete on public.%I for delete to authenticated using (public.current_app_role() = ''Yönetici'')', table_name, table_name);
  end loop;
end $$;

insert into storage.buckets (id, name, public, file_size_limit)
values ('project-files', 'project-files', false, 15728640)
on conflict (id) do update set public = false, file_size_limit = 15728640;

drop policy if exists project_files_storage_read on storage.objects;
create policy project_files_storage_read on storage.objects for select to authenticated
using (bucket_id = 'project-files');
drop policy if exists project_files_storage_insert on storage.objects;
create policy project_files_storage_insert on storage.objects for insert to authenticated
with check (bucket_id = 'project-files' and public.current_app_role() in ('Yönetici','Kullanıcı'));
drop policy if exists project_files_storage_delete on storage.objects;
create policy project_files_storage_delete on storage.objects for delete to authenticated
using (bucket_id = 'project-files' and public.current_app_role() = 'Yönetici');

-- Mevcut tarayıcı arayüzünün ortak ve sürüm kontrollü uygulama durumu.
-- JSONB yapısı ilk geçişte ekranları yeniden yazmadan çok kullanıcılı çalışmayı sağlar.
create table if not exists public.app_state (
  id text primary key check (id = 'main'),
  payload jsonb not null default '{}'::jsonb,
  version bigint not null default 0,
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

insert into public.app_state (id, payload, version)
values ('main', '{}'::jsonb, 0)
on conflict (id) do nothing;

alter table public.app_state enable row level security;

drop policy if exists app_state_read on public.app_state;
create policy app_state_read on public.app_state for select to authenticated
using (true);

-- Kayıtlar doğrudan güncellenmez; sürüm kontrolü yapan RPC kullanılır.
create or replace function public.save_app_state(
  expected_version bigint,
  new_payload jsonb
)
returns table(version bigint, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_version bigint;
  saved_at timestamptz;
begin
  if public.current_app_role() not in ('Yönetici', 'Kullanıcı') then
    raise exception 'POLPRO_WRITE_FORBIDDEN' using errcode = '42501';
  end if;

  if new_payload is null or jsonb_typeof(new_payload) <> 'object' then
    raise exception 'POLPRO_INVALID_PAYLOAD' using errcode = '22023';
  end if;

  select state.version
    into current_version
    from public.app_state state
   where state.id = 'main'
   for update;

  if current_version is distinct from expected_version then
    raise exception 'POLPRO_VERSION_CONFLICT expected %, current %', expected_version, current_version
      using errcode = '40001';
  end if;

  update public.app_state
     set payload = new_payload,
         version = current_version + 1,
         updated_by = auth.uid(),
         updated_at = now()
   where id = 'main'
   returning app_state.version, app_state.updated_at
        into version, saved_at;

  updated_at := saved_at;
  return next;
end;
$$;

revoke all on function public.save_app_state(bigint, jsonb) from public;
grant execute on function public.save_app_state(bigint, jsonb) to authenticated;

alter table public.app_state replica identity full;
do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'app_state'
  ) then
    alter publication supabase_realtime add table public.app_state;
  end if;
end $$;
